extends: [
  "airbnb",
  "prettier",
  "plugin:react/recommended"
]

plugins: [
  "react",
]

parser: "babel-eslint"

parserOptions:
  ecmaVersion: 7
  sourceType: "module"
  ecmaFeatures:
    jsx: true

env:
  browser: true
  es6: true
  node: true

rules:
  # -------------
  # General Rules
  # -------------

  import/no-extraneous-dependencies: [0, { devDependencies: true }]
  import/no-named-as-default: 2
  import/no-unresolved: 0
  import/extensions: 0

  # -----------
  # React Rules
  # -----------

  react/require-default-props: 0
  react/forbid-prop-types: 0

  # --------
  # JSX a11y
  # --------

  jsx-a11y/anchor-is-valid: 0
